name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:  # 手動実行も可能にする

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Configure twine for GitHub Packages
      run: |
        echo "[distutils]" > ~/.pypirc
        echo "index-servers = github" >> ~/.pypirc
        echo "" >> ~/.pypirc
        echo "[github]" >> ~/.pypirc
        echo "repository = https://pypi.pkg.github.com/keides2/" >> ~/.pypirc
        echo "username = __token__" >> ~/.pypirc
        echo "password = ${{ secrets.GITHUB_TOKEN }}" >> ~/.pypirc
    
    - name: Publish to GitHub Packages
      run: |
        twine upload --repository github dist/*
